# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ManageStore' do

  pod 'RAMAnimatedTabBarController'
  pod 'ShadowView'

  target 'ManageStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ManageStoreUITests' do
    # Pods for testing
  end

end
